config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :departments, except: :show
  resources :users

  root 'users#directory'

  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'
  match '/directory', to: 'users#directory', via: 'get'
  match '/directory', to: 'users#directory', via: 'post'
  match '/users_filter', to: 'users#index', via: 'post'
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :department

  default_scope -> { order('last_name, first_name') }
  scope :in_department, lambda { |dept_id| where(department_id: dept_id) }
  scope :with_name,
        lambda { |name| where("lower(first_name) LIKE ? or lower(last_name) LIKE ?",
                              "%#{name.downcase}%", "%#{name.downcase}%" ) }

  before_create :create_remember_token

  validates :first_name, :last_name, presence: true, length: { maximum: 50 }
  validates :department_id, presence: true
  validates :phone, presence: true,
             format: { with: EmployeeDirectory::VALID_PHONE_REGEX }
  validates :email, presence: true,
            format: { with: EmployeeDirectory::VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :address, length: { maximum: 200 }
  validates :start_date, date: true
  validates :birthday, date: true, allow_blank: true
  validates :password, length: { minimum: 6 }, on: :create
  validates :password, length: { minimum: 6 }, on: :update, if: :password

  has_secure_password
  self.per_page = 15

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ActionRestrictions
  before_action :logged_in_user, except: [:directory, :show]
  before_action :admin_user, except: [:directory, :edit, :update, :show]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :edit_self_only, only: [:edit, :update]

  # GET /users
  def index
    get_users
  end

  def directory
    get_users
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    render :form
  end

  # GET /users/1/edit
  def edit
    render :form
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'User was successfully created.'
      redirect_to @user
    else
      render :form
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      flash[:success] = 'User was successfully updated.'
      redirect_to @user
    else
      render :form
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    respond_to do |format|
      format.js { render template: 'shared/remove_row',
                         locals: { target_object: @user } }
      format.html { redirect_to users_url }
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      if current_user.admin?
        # Allow admins more access
        params.require(:user).permit(:first_name, :last_name, :department_id,
                                     :phone, :email, :password, :password_confirmation,
                                     :address, :start_date, :birthday, :admin)
      else
        # Allow general users less access
        params.require(:user).permit(:phone, :email, :password, :password_confirmation,
                                     :address)
      end
    end

    def get_users
      name_to_find = params[:user_filter_string]
      dept_to_find = params[:user_filter_type] == 'dep' ? params[:user_filter_department] : nil
      @users = find_users_by_page(name_to_find, dept_to_find, params[:page])
    end

    def find_users_by_page(name, department, page)
      found_users = case
        when name && department
          # Search by both name and department
          User.with_name(name).in_department(department)
        when name && !department
          # Only search by name
          User.with_name(name)
        when !name && department
          # Only search by department
          User.in_department(department)
        else
          # No search criteria so return all
          User.all
      end
      # Return paginated result
      found_users.paginate(page: page)
    end

    def edit_self_only
      # Unless the user is an admin, they may only edit their own record
      unless current_user.admin?
        if current_user != User.find(params[:id])
          # Trying to edit someone else, so redirect to their own record
          redirect_to edit_user_url(current_user)
        end
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def user_form_legend
    # Return an appropriate legend name depending on the current action
    case action_name
      when 'new', 'create'
        'Create User'
      when 'edit', 'update'
        'Edit User'
      else
        'User Maintenance'
    end
  end

  def non_admin_disable
    # Return true for disabled flag on certain fields non-admins can't edit
    !current_user.admin?
  end

  def gravatar_for(user, options={ size: 150 })
    # Returns the Gravatar for the provided user
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.first_name + ' ' + user.last_name,
              class: 'user-gravatar')
  end

  def view_option_check_for(option, param)
    if option == 'all' && param[:user_filter_type] == 'all'
      true
    elsif option == 'dep' && param[:user_filter_type] == 'dep'
      true
    elsif option == 'all' && param[:user_filter_type] == nil
      true
    else
      false
    end
  end

  def filter_panel_class_for(collapsed = false)
    if collapsed
      "visible-xs visible-sm"
    else
      "visible-md visible-lg"
    end
  end

  def filter_panel_title_for(title, collapsed = false)
    if collapsed
      output = "<a data-toggle='collapse' href='#collapseOne'>"
      output += title + "<b class='caret'></b></a>"
      output.html_safe
    else
      title
    end
  end

  def filter_panel_body_for(collapsed = false, &block)
    if collapsed
      content_tag(:div, capture(&block), id: 'collapseOne',
                  class: 'panel-collapse collapse')
    else
      capture(&block)
    end
  end
end

app/views/users/_directory_entry.html.erb
<tr id="<%= directory_entry.id %>">
  <td><div class='user-detail'>
    <%= link_to directory_entry.last_name, user_path(directory_entry) %>
  </div></td>
  <td><div class='user-detail'>
    <%= link_to directory_entry.first_name, user_path(directory_entry) %>
  </div></td>
  <td><%= directory_entry.department.name %></td>
  <td><%= directory_entry.phone %></td>
</tr>

app/views/users/_filter_form.html.erb
<!--USER FILTER FORM-->
<%= bootstrap_form_tag url: filter_path, layout: :horizontal,
                       control_col: 'col-xs-12' do |f| %>

    <%= f.search_field :user_filter_string, hide_label: true, placeholder: 'Search',
                       class: 'set-focus', value: params[:user_filter_string] %>

    <%= f.radio_button :user_filter_type, 'all', label: "All Users",
                       checked: view_option_check_for('all', params),
                       class: 'view-option' %>
    <%= f.radio_button :user_filter_type, 'dep', label: "Users by Department",
                       checked: view_option_check_for('dep', params),
                       class: 'view-option' %>


  <div class="dept-list" <% if (params[:user_filter_type] == 'all' || params[:user_filter_type] == nil) %> style="display: none;" <% end %> >

    <%= f.select :user_filter_department,
                 options_for_select(Department.all.collect{ |d| [d.name, d.id]},
                                    params[:user_filter_department]),
                                    hide_label: true, prompt: 'Select Department...' %>
  </div>

  <div class="filter-apply">
    <%= f.submit class: 'btn btn-primary', value: "Apply" %>
  </div>

<% end %>

app/views/users/_filter_panel.html.erb
<!-- Side Panel -->
<div class="panel panel-default <%= filter_panel_class_for(collapsed) %>">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= filter_panel_title_for("View Options", collapsed) %>
    </h3>
  </div>
  <%= filter_panel_body_for(collapsed) do %>
    <div class="panel-body">
      <%= render 'filter_form', filter_path: filter_path %>
    </div> <!-- panel body -->
  <% end %>
</div> <!-- side panel -->

app/views/users/_gravatar_panel.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      User Photo Preview
    </h3>
  </div>
  <div class="panel-body">
    <div class="image-preview">
      <%= gravatar_for @user %>
    </div>
    <div>
      <br />
      <p><i>User image is loaded automatically based on email address via the
        <a href="https://www.gravatar.com" target="_blank">
          Gravatar</a> service.</i></p>
    </div>
  </div> <!-- panel body -->
</div> <!-- panel -->

app/views/users/_side_panel.html.erb
<!-- SIDE PANEL -->
<div class="col-md-3 column">

  <%= render partial: 'filter_panel', locals: { collapsed: true, filter_path: filter_path } %>

  <%= render partial: 'filter_panel', locals: { collapsed: false, filter_path: filter_path } %>

</div> <!-- side panel -->

app/views/users/_user.html.erb
<tr id="<%= user.id %>">
  <td>
    <ul class="user-actions">
      <li class="user-action-item">
        <%= link_to 'Edit', edit_user_path(user) %>
      </li>
      <li class="user-action-item">
        <%= link_to 'Delete', user,
                    data: { confirm: "Are you sure you want to delete '#{user.first_name} #{user.last_name}'?" },
                    method: :delete, remote: true %>

      </li>
  </td>
  <td><%= user.last_name %></td>
  <td><%= user.first_name %></td>
  <td><%= user.department.name %></td>
</tr>

app/views/users/_user_detail.html.erb
<%= bootstrap_form_for(@user, layout: :horizontal,
                       label_col: 'col-lg-3', control_col: 'col-lg-9') do |f| %>

  <legend><%= "#{@user.first_name} #{@user.last_name}" %></legend>

  <%= f.static_control nil, label: 'Department' do %>
    <%= @user.department.name %>
  <% end %>

  <%= f.static_control :phone %>

  <% if current_user %>
    <% # The following fields are only shown to logged in users %>
    <%= f.static_control :email %>

    <%= f.static_control nil, label: 'Address' do %>
      <%= simple_format(@user.address) %>
    <% end %>

    <%= f.static_control nil, label: 'Start Date' do %>
      <%= @user.start_date.strftime("%-m/%-d/%Y") %>
    <% end %>

    <%= f.static_control nil, label: 'Birthday' do %>
      <% if current_user.admin? %>
        <% # Show the birthday year for admins %>
        <%= @user.birthday.strftime("%-m/%-d/%Y") %>
      <% else %>
        <% # Non-admin users only see birthday month and day %>
        <%= @user.birthday.strftime("%-B %-d") %>
      <% end %>
    <% end %>

    <% if current_user.admin? %>
      <% # Only show the admin setting to admins %>
      <%= f.static_control nil, label: 'Administrator?' do %>
        <%= @user.admin? ? 'Yes' : 'No' %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_view_form.html.erb
<%= bootstrap_form_tag url: filter_path, layout: :horizontal,
                       control_col: 'col-xs-12' do |f| %>

    <%= f.search_field :user_search, hide_label: true, placeholder: 'Search',
                       class: 'set-focus', value: params[:user_search] %>

    <%= f.radio_button :user_view, 'all', label: "All Users",
                       checked: view_option_check_for('all', params),
                       class: 'view-option' %>
    <%= f.radio_button :user_view, 'dep', label: "Users by Department",
                       checked: view_option_check_for('dep', params),
                       class: 'view-option' %>


  <div class="dept-list" <% if (params[:user_view] == 'all' || params[:user_view] == nil) %> style="display: none;" <% end %> >

    <%= f.select :view_department_id,
                 options_for_select(Department.all.collect{ |d| [d.name, d.id]},
                                    params[:view_department_id]),
                                    hide_label: true, prompt: 'Select Department...' %>
  </div>

  <div class="filter-apply">
    <%= f.submit class: 'btn btn-primary', value: "Apply" %>
  </div>

<% end %>

app/views/users/directory.html.erb
<!-- ********************* MAIN CONTENT ********************* -->
<div class="row clearfix">
  <%= render 'users/side_panel', filter_path: directory_path %>
  <!-- USER LIST -->
  <div class="col-md-9 column">
    <div class="panel panel-default table-panel">
      <div class="panel-body">
        <table class="table table-striped table-hover">
          <thead>
          <tr>
            <th>Last Name</th>
            <th>First Name</th>
            <th>Department</th>
            <th>Phone</th>
            </a>
          </tr>
          </thead>
          <tbody data-link="row">
          <% if @users.any? %>
            <%= render partial: 'directory_entry', collection: @users, as: :directory_entry %>
          <% else %>
            <tr><td colspan="4" class="no-records">No Matching Records</td></tr>
          <% end %>
          </tbody>
        </table>
        <%= will_paginate @users, renderer: BootstrapPagination::Rails,
                          class: 'pagination-sm',
                          params: { user_filter_type: params[:user_filter_type],
                                    user_filter_department: params[:user_filter_department],
                                    user_filter_string: params[:user_filter_string] }%>
      </div> <!-- panel body -->
    </div>  <!-- panel -->
  </div> <!-- col user list -->

</div> <!-- row main content ************************************** -->

app/views/users/form.html.erb
<!-- ********************* MAIN CONTENT ********************* -->
<div class="row clearfix">

  <div class="col-md-8 column">
    <%= render partial: 'shared/form_errors', locals: { form_target: @user } %>

    <!--USER FORM-->
    <div class="well">
      <%= bootstrap_form_for(@user, layout: :horizontal,
                             label_col: 'col-lg-2', control_col: 'col-lg-10') do |f| %>

        <legend><%= user_form_legend %></legend>

        <!--First Name-->
        <%= f.text_field :first_name, placeholder: 'First Name',
                         label: 'First Name', class: 'set-focus',
                         disabled: non_admin_disable %>

        <!--Last Name-->
        <%= f.text_field :last_name, placeholder: 'Last Name',
                         label: 'Last Name', disabled: non_admin_disable %>

        <!--Department-->
        <% if current_user.admin? %>
          <%= f.collection_select :department_id, Department.all,
                                  :id, :name, prompt: true %>
        <% else %>
          <%= f.text_field :department_id, value: @user.department.name, disabled: true %>
        <% end %>

        <!--Phone Number-->
        <%= f.phone_field :phone, class: 'mask-phone', placeholder: 'xxx-xxx-xxxx',
                          label: 'Phone Number' %>

        <!--Email-->
        <%= f.email_field :email, placeholder: 'Email' %>

        <!--Password-->
        <%= f.password_field :password, placeholder: 'Password' %>

        <!--Password Confirmation-->
        <%= f.password_field :password_confirmation, placeholder: 'Confirm Password',
                             label: 'Confirm Password' %>

        <!--Mailing Address-->
        <%= f.text_area :address, rows: 5, placeholder: 'Mailing Address' %>

        <!--Start Date-->
        <%= f.date_field :start_date, label: 'Start Date', disabled: non_admin_disable %>

        <!--Birthday-->
        <% if current_user.admin? %>
          <%= f.date_field :birthday %>
        <% else %>
          <%= f.text_field :birthday, value: @user.birthday.strftime("%-m/%-d"),
                           disabled: non_admin_disable %>
        <% end %>

        <% if current_user.admin? %>
          <!--Application Administrator-->
          <%= f.form_group :admin, label: { text: "Administrator?" } do %>
            <%= f.radio_button :admin, 0, label: "No", checked: !@user.admin? %>
            <%= f.radio_button :admin, 1, label: "Yes", checked: @user.admin? %>
          <% end %>
        <% end %>

        <%= f.form_group do %>
          <%= f.submit class: 'btn btn-success' %>
        <% end %>
      <% end %>

    </div> <!-- well -->

  </div> <!-- col user form -->
  <% unless action_name == 'new' || action_name == 'create' %>
    <!-- SIDE PANEL -->
    <div class="col-md-4 column">
      <%= render 'gravatar_panel' %>
    </div> <!-- col side panel -->
  <% end %>

</div>  <!-- row main content ************************************** -->

<%= link_to 'Go Back  ', users_path %>

app/views/users/index.html.erb
<!-- ********************* MAIN CONTENT ********************* -->
<div class="row clearfix">
  <%= render 'users/side_panel', filter_path: users_filter_path %>
  <!-- USER LIST -->
  <div class="col-md-9 column">
    <div class="panel panel-default table-panel">
      <div class="panel-heading">
        <h3 class="panel-title">
          User Maintenance
        </h3>
        <small><%= link_to 'Create New User', new_user_path,
                           class: 'new-user-link' %></small>
      </div>
      <div class="panel-body">
        <table class="table table-striped table-hover">
          <thead>
          <tr>
            <th>Action</th>
            <th>Last Name</th>
            <th>First Name</th>
            <th>Department</th>
            </a>
          </tr>
          </thead>
          <tbody data-link="row">
          <% if @users.any? %>
            <%= render @users %>
          <% else %>
            <tr><td colspan="4" class="no-records">No Matching Records</td></tr>
          <% end %>
          </tbody>
        </table>
        <%= will_paginate @users, renderer: BootstrapPagination::Rails,
                          class: 'pagination-sm',
                          params: { user_filter_type: params[:user_filter_type],
                                    user_filter_department: params[:user_filter_department],
                                    user_filter_string: params[:user_filter_string] }%>
      </div> <!-- panel body -->
    </div>  <!-- panel -->
  </div> <!-- col user list -->

</div> <!-- row main content ************************************** -->

app/views/users/show.html.erb
<!-- ********************* MAIN CONTENT ********************* -->
<div class="row clearfix">

  <div class="col-md-8 column">

    <%= render partial: 'shared/app_flash',
               locals: { box_size: :large } %>

    <div class="well">
      <div class="row">
        <!-- SIDE PANEL -->
        <div class="col-md-4">
          <%= gravatar_for @user %>
        </div> <!-- col side panel -->
        <!--USER DETAIL-->
        <div class="col-md-8">
          <%= render 'user_detail' %>
        </div> <!--col user detail-->
      </div> <!-- row panel -->
    </div> <!-- well -->

    <%= link_to 'Go Back  ', directory_path %>

  </div> <!-- col user form -->

</div>  <!-- row main content ************************************** -->