config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :departments, except: :show
  resources :users

  root 'users#directory'

  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'
  match '/directory', to: 'users#directory', via: 'get'
  match '/directory', to: 'users#directory', via: 'post'
  match '/users_filter', to: 'users#index', via: 'post'
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :users

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :name, :location, length: { maximum: 50 }
  validates :phone, format: { with: EmployeeDirectory::VALID_PHONE_REGEX },
            allow_blank: true

  self.per_page = 15
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  include ActionRestrictions
  before_action :logged_in_user
  before_action :admin_user
  before_action :set_department, only: [:edit, :update, :destroy]
  before_action :check_for_assigned_users, only: :destroy

  # GET /departments
  def index
    @departments = Department.paginate(page: params[:page])
  end

  # GET /departments/new
  def new
    @department = Department.new
    render :form
  end

  # GET /departments/1/edit
  def edit
    render :form
  end

  # POST /departments
  def create
    @department = Department.new(department_params)
    if @department.save
      flash[:success] = "Department was successfully created."
      redirect_to departments_url
    else
      render :form
    end
  end

  # PATCH/PUT /departments/1
  def update
    if @department.update(department_params)
      flash[:success] = 'Department was successfully updated.'
      redirect_to departments_url
    else
      render :form
    end
  end

  # DELETE /departments/1
  def destroy
    @department.destroy
    respond_to do |format|
      format.js { render template: 'shared/remove_row',
                         locals: { target_object: @department } }
      format.html { redirect_to departments_url }
    end
  end

  private

    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name, :location, :phone)
    end

    # Don't allow deletion of departments with assigned users
    def check_for_assigned_users
      if @department.users.any?
        flash[:error] = "Can't delete department with assigned users."
        flash.keep(:error)
        render js: "window.location = '#{departments_url}'"
        false
      end
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper

  def department_form_legend
    # Return an appropriate legend name depending on the current action
    case action_name
      when 'new', 'create'
        'Create Department'
      when 'edit', 'update'
        'Edit Department'
      else
        'Department Maintenance'
    end
  end
end

app/views/departments/_department.html.erb
<tr id="<%= department.id %>">
  <td>
    <ul class="dept-actions">
      <li class="dept-action-item">
        <%= link_to 'Edit', edit_department_path(department) %>
      </li>
      <li class="dept-action-item">
        <%= link_to 'Delete', department,
                    data: { confirm: "Are you sure you want to delete '#{department.name}'?" },
                    method: :delete, remote: true %>
      </li>
  </td>
  <td><%= department.name %></td>
  <td><%= department.location %></td>
  <td><%= department.phone %></td>
</tr>

app/views/departments/form.html.erb
<!-- ********************* MAIN CONTENT ********************* -->
<div class="row clearfix">

  <div class="col-md-8 column">
    <%= render partial: 'shared/form_errors', locals: { form_target: @department } %>

    <!-- DEPARTMENT FORM -->
    <div class="well">
      <%= bootstrap_form_for(@department, layout: :horizontal,
                             label_col: 'col-lg-3', control_col: 'col-lg-9') do |f| %>

        <legend><%= department_form_legend %></legend>

        <!--Department Name -->
        <%= f.text_field :name, placeholder: 'Department Name',
                         label: 'Department Name', class: 'set-focus' %>

        <!--Location-->
        <%= f.text_field :location, placeholder: 'Location' %>

        <!--Phone-->
        <%= f.phone_field :phone, class: 'mask-phone', placeholder: 'xxx-xxx-xxxx' %>

        <%= f.form_group do %>
          <%= f.submit class: 'btn btn-success' %>
        <% end %>
      <% end %>
    </div> <!-- well -->
    <%= link_to 'Go Back  ', departments_path %>
  </div> <!-- col dept form -->

</div>  <!-- row main content ************************************** -->

app/views/departments/index.html.erb
<!-- ********************* MAIN CONTENT ********************* -->
<div class="row clearfix">

  <div class="col-md-9 column">

    <%= render partial: 'shared/app_flash',
               locals: { box_size: :large } %>

    <!-- DEPARTMENT LIST -->
    <div class="panel panel-default table-panel">
      <div class="panel-heading">
        <h3 class="panel-title">
          Department Maintenance
        </h3>
        <small><%= link_to 'Create New Department', new_department_path,
                           class: 'new-dept-link' %></small>
      </div>
      <div class="panel-body">
        <table class="table table-striped table-hover ">
          <thead>
          <tr>
            <th>Action</th>
            <th>Department Name</th>
            <th>Location</th>
            <th>Phone</th>
          </tr>
          </thead>
          <tbody>
            <%= render @departments %>
          </tbody>
        </table>
        <%= will_paginate @departments, renderer: BootstrapPagination::Rails,
                          class: 'pagination-sm' %>
      </div> <!-- panel body -->
    </div> <!-- panel -->
  </div> <!-- col dept list -->

</div> <!-- row main content ************************************** -->