config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :departments, except: :show
  resources :users

  root 'users#directory'

  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'
  match '/directory', to: 'users#directory', via: 'get'
  match '/directory', to: 'users#directory', via: 'post'
  match '/users_filter', to: 'users#index', via: 'post'
end

app/views/layouts/_logged_in_links.html.erb
<div class="navbar-collapse collapse navbar-responsive-collapse">
  <ul class="nav navbar-nav navbar-right">
    <li class="<%= active_class_for :directory %>">
      <%= link_to 'Directory', directory_path %>
    </li>
    <li class="<%= active_class_for :profile %>">
      <%= link_to 'Edit My Profile', edit_user_path(current_user) %>
    </li>
    <% if current_user.admin? %>
      <li class="dropdown <%= active_class_for :maintenance %>">
        <a href="#" class="dropdown-toggle"
           data-toggle="dropdown">Maintenance <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Users', users_path %></li>
          <li><%= link_to 'Departments', departments_path %></li>
        </ul>
      </li>
    <% end %>
    <li class="<%= active_class_for :logout %>">
      <%= link_to 'Logout', logout_path, method: :delete %>
    </li>
  </ul>
</div>

app/views/layouts/_logged_out_links.html.erb
<div class="navbar-collapse collapse navbar-responsive-collapse">
  <ul class="nav navbar-nav navbar-right">
    <li class="<%= active_class_for :login %>"><%= link_to 'Login', login_path %></li>
  </ul>
</div>

app/views/layouts/_meta.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Toy corporate phone book application">
<meta name="author" content="Russ Martin">

app/views/layouts/_navbar.html.erb
<!-- ********************* NAVIGATION BAR ********************* -->
<div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to Rails.configuration.company_name, root_path, class:'navbar-brand' %>
  </div>
  <% if logged_in? %>
    <%= render 'layouts/logged_in_links' %>
  <% else %>
    <%= render 'layouts/logged_out_links' %>
  <% end %>
</div> <!-- navbar *********************************************-->

app/views/layouts/_page_footer.html.erb
<!-- ********************* PAGE FOOTER ********************* -->
<div class="row">
  <div class="col-xs-12">&nbsp;</div>
  <div class="col-xs-12">&nbsp;</div>
  <%= debug(params) if Rails.env.development? %>
</div> <!-- row page footer ********************************-->

app/views/layouts/_page_header.html.erb
<!-- ********************* PAGE HEADER ********************* -->
<div class="row clearfix">
  <div class="col-xs-12 column">
    <div class="page-header">
      <h1>
        <%= Rails.configuration.application_name %>
      </h1>
    </div>
  </div>
</div> <!-- row page header ********************************-->

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render 'layouts/meta' %>
    <title><%= Rails.configuration.application_name %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/page_header' %>
      <%= yield %>
      <%= render 'layouts/page_footer' %>
    </div> <!-- container -->
  </body>
</html>